"""
Implements "CcbCipher", a custom stream cipher based on the ChaCha family.

This cipher is used to encrypt and decrypt gRPC payloads and server tokens for
the Takasho API. It operates on a 512-bit state initialized with a 256-bit key
and a 96-bit nonce.

Key characteristics:
- **Dynamic Round Count**: The number of transformation rounds is not fixed.
  It is calculated on initialization based on a value derived from the key
  and nonce, which is then used to index into a `ROUND_GAPS` lookup table.
- **Keystream Generation**: For each 64-byte block of data, a unique
  keystream block is generated by repeatedly applying a quarter-round
  function (add-rotate-xor) to the state matrix. The process iterates
  over columns and then diagonals for the dynamically determined number of
  rounds.
- **Stateless Transformation**: The public `transform` method provides a
  stateless interface for encryption and decryption. It generates the
  keystream on-the-fly and XORs it with the input data, making it suitable
  for both operations.

:param key: A 32-byte (256-bit) secret key.
:param nonce: A 12-byte (96-bit) number used once per key.

"""

import struct
from configuration.manger_config import config


class CcbCipher:

    SIGMA = bytes.fromhex(config.secrets['CcbCipher']['Sigma'])
    ROUND_GAPS = bytes.fromhex(config.secrets['CcbCipher']['RoundGaps'])

    @staticmethod
    def _add32(a, b): return (a + b) & 0xFFFFFFFF
    @staticmethod
    def _ror32(v, s): return ((v >> s) | (v << (32 - s))) & 0xFFFFFFFF
    @staticmethod
    def _rol32(v, s): return ((v << s) | (v >> (32 - s))) & 0xFFFFFFFF

    def __init__(self, key: bytes, nonce: bytes):
        if len(key) != 32:   raise ValueError("The key must be 32 bytes")
        if len(nonce) != 12: raise ValueError("The nonce must be 12 bytes")
        self.state = [0]*16
        self.state[0:4]   = struct.unpack("<4I", self.SIGMA)
        self.state[4:12]  = struct.unpack("<8I", key)
        self.state[12]    = 0
        self.state[13:16] = struct.unpack("<3I", nonce)
        s5, s10, s12 = self.state[4], self.state[9], self.state[11]
        n0, n1, n2   = self.state[13], self.state[14], self.state[15]
        cv  = self._add32((self._add32(s10, s5) ^ s12), (self._add32(n1,  n0) ^ n2))
        idx = (((cv >> 7) & 2) | ((cv >> 2) & 1) | ((cv >> 13) & 4) | ((cv >> 2) & 8))
        self.rounds = 10 - self.ROUND_GAPS[idx]
        self._base  = list(self.state)


    def _keystream_block(self, counter: int) -> bytes:
        x = list(self._base)
        x[12] = self._add32(x[12], counter)

        initial_state_with_counter = list(x)

        for _ in range(self.rounds):

            x[0]  = self._add32(x[0],  x[4]);  x[12] = self._ror32(x[12] ^ x[0], 16)
            x[8]  = self._add32(x[8],  x[12]); x[4]  = self._rol32(x[4]  ^ x[8], 12)
            x[0]  = self._add32(x[0],  x[4]);  x[12] = self._rol32(x[12] ^ x[0], 8)
            x[8]  = self._add32(x[8],  x[12]); x[4]  = self._rol32(x[4]  ^ x[8], 7)


            x[1]  = self._add32(x[1],  x[5]);  x[13] = self._ror32(x[13] ^ x[1], 16)
            x[9]  = self._add32(x[9],  x[13]); x[5]  = self._rol32(x[5]  ^ x[9], 12)
            x[1]  = self._add32(x[1],  x[5]);  x[13] = self._rol32(x[13] ^ x[1], 8)
            x[9]  = self._add32(x[9],  x[13]); x[5]  = self._rol32(x[5]  ^ x[9], 7)


            x[2]  = self._add32(x[2],  x[6]);  x[14] = self._ror32(x[14] ^ x[2], 16)
            x[10] = self._add32(x[10], x[14]); x[6]  = self._rol32(x[6]  ^ x[10], 12)
            x[2]  = self._add32(x[2],  x[6]);  x[14] = self._rol32(x[14] ^ x[2], 8)
            x[10] = self._add32(x[10], x[14]); x[6]  = self._rol32(x[6]  ^ x[10], 7)


            x[3]  = self._add32(x[3],  x[7]);  x[15] = self._ror32(x[15] ^ x[3], 16)
            x[11] = self._add32(x[11], x[15]); x[7]  = self._rol32(x[7]  ^ x[11], 12)
            x[3]  = self._add32(x[3],  x[7]);  x[15] = self._rol32(x[15] ^ x[3], 8)
            x[11] = self._add32(x[11], x[15]); x[7]  = self._rol32(x[7]  ^ x[11], 7)


            x[0]  = self._add32(x[0],  x[5]);  x[15] = self._ror32(x[15] ^ x[0], 16)
            x[10] = self._add32(x[10], x[15]); x[5]  = self._rol32(x[5]  ^ x[10], 12)
            x[0]  = self._add32(x[0],  x[5]);  x[15] = self._rol32(x[15] ^ x[0], 8)
            x[10] = self._add32(x[10], x[15]); x[5]  = self._rol32(x[5]  ^ x[10], 7)


            x[1]  = self._add32(x[1],  x[6]);  x[12] = self._ror32(x[12] ^ x[1], 16)
            x[11] = self._add32(x[11], x[12]); x[6]  = self._rol32(x[6]  ^ x[11], 12)
            x[1]  = self._add32(x[1],  x[6]);  x[12] = self._rol32(x[12] ^ x[1], 8)
            x[11] = self._add32(x[11], x[12]); x[6]  = self._rol32(x[6]  ^ x[11], 7)


            x[2]  = self._add32(x[2],  x[7]);  x[13] = self._ror32(x[13] ^ x[2], 16)
            x[8]  = self._add32(x[8],  x[13]); x[7]  = self._rol32(x[7]  ^ x[8], 12)
            x[2]  = self._add32(x[2],  x[7]);  x[13] = self._rol32(x[13] ^ x[2], 8)
            x[8]  = self._add32(x[8],  x[13]); x[7]  = self._rol32(x[7]  ^ x[8], 7)


            x[3]  = self._add32(x[3],  x[4]);  x[14] = self._ror32(x[14] ^ x[3], 16)
            x[9]  = self._add32(x[9],  x[14]); x[4]  = self._rol32(x[4]  ^ x[9], 12)
            x[3]  = self._add32(x[3],  x[4]);  x[14] = self._rol32(x[14] ^ x[3], 8)
            x[9]  = self._add32(x[9],  x[14]); x[4]  = self._rol32(x[4]  ^ x[9], 7)


        ks = [self._add32(x[i], initial_state_with_counter[i]) for i in range(16)]
        return struct.pack("<16I", *ks)

    def transform(self, data: bytes) -> bytes:
        out, counter = bytearray(), 0
        for off in range(0, len(data), 64):
            ks = self._keystream_block(counter)
            out.extend(b ^ k for b, k in zip(data[off:off+64], ks))
            counter += 1
        return bytes(out)