; ==================================================
;  HeartGold-PCKT Master Configuration File
; ==================================================

[AppInfo]
AppVersion = 1.4.0
BuildVersion = 
SdkVersion = Unity-3.9.0-016a4b5c812
TakashoSdkVersion = 2.0.0
ProtocolVersion = v7.0.3

[DeviceInfo]
Manufacturer = Samsung
OsType = Android

[NetworkInfo]
NetworkType = wifi
Carrier = TIM

[LocaleInfo]
TimeZoneOffset = 7200000


[NintendoBaaS_Endpoints]
Url = 
Audience = 

[TakashoGRPC_Endpoints]
ServerAddress = 


[NintendoBaaS_Secrets]
HotpKey = 

[TakashoGRPC_Secrets]
ServerTokenString = 
ServerTokenDecryptionKey = 
ServerTokenDecryptionNonce = 

[CcbCipher_Secrets]
Sigma = 
RoundGaps = 


[MongoDB]
Uri = 
DatabaseName = 
CollectionPack = 
CollectionGodPack = 
CollectionReroll = 


[StaticHashes]
AssetAladdinHash = 
MasterMemoryAladdinHash = 
AppVersionHashKey = 


[Proxy]
Host = 
Port = 
Username = 
Password = 
Enabled = 


[Collector]
MaxRetries = 
CyclesPerIp = 

[Leveler]
AccountsPerIp = 

[Maker]
CyclesPerIp = 


[Logging]
LogToConsole = false


[Reroller]
AccountsPerIp = 

[Cacher]
AccountsPerIp = 

[FirstShop]
AccountsPerIp = 

[MonthlyShop]
AccountsPerIp = 
